### PR TITLE
Enable clean step for AVX512 windows buildbot job

### PR DESCRIPTION
**Pull request by DoyleLi**

### CODE REVIEW

**Review by andreil99 — APPROVED** [review]
LGTM.

**Review by gkistanova — APPROVED** [review]
LGTM.

**Comment by DoyleLi** [comment]
Ping.
Hi @gkistanova  could you please help to merge the PR. Thank you~

**Comment by gkistanova** [comment]
Did you try to click the "Squash and merge" button right below? If you did, what happened?

**Comment by DoyleLi** [comment]
No I cannot see the "Squash and merge" button. It seems I need to apply for write access?

"Only those with [write access](https://docs.github.com/articles/what-are-the-different-access-permissions) to this repository can merge pull requests."

**Comment by gkistanova** [comment]
No worries. I merged this PR for you.

**Comment by DoyleLi** [comment]
Got it. Thank you so much!

**Pull request merged**
