### PR TITLE
Add new LLDB remote-linux cross builder 'lldb-remote-linux-ubuntu'.

### PR DESCRIPTION
**Pull request by vvereschaka**
x86_64/Linux Ubuntu host and Aarch64/Linux Ubuntu remote target.

Also added new 'as-builder-9' worker.

### CODE REVIEW

**Comment by vvereschaka** [comment]
depends on #222, #223, #224

**Comment by vvereschaka** [comment]
still draft, but should be ready around evening

**Comment by vvereschaka** [comment]
The initial configuration for the lldb remote -linux builder on the Linux Ubuntu host.
The configuration will get changed later while moving the local lldb patches into the mainline.

@gkistanova would you assign the same pwd for the worker as for other `as-builder-*` workers?

**Review by gkistanova — APPROVED** [review]
Thanks, Vlad!
LGTM.

**Comment by gkistanova** [comment]
Please feel free to connect to staging.

**Comment by vvereschaka** [comment]
Thank you @gkistanova!

The worker has been connected to the staging master
https://lab.llvm.org/staging/#/builders/200

We are going to keep it running on the staging bot till it gets became the "green" one.

**Pull request merged**
