### PR TITLE
Make builder llvm-new-debug-iterators do clean builds.

### PR DESCRIPTION
**Pull request by dyung**
Set option to have the build bot do clean builds.

### CODE REVIEW

**Review by gkistanova — APPROVED** [review]
LGTM.

**Comment by joker-eph** [comment]
There is no motivation exposed here: can you clarify on why this change?

**Comment by dyung** [comment]
> There is no motivation exposed here: can you clarify on why this change?

The bot was previously doing "dirty" builds while it was in testing and waiting for an upstream commit to go in. Now that the commit is in and it added a new CMake argument, I was afraid that doing dirty builds may not get the CMake argument to stick so we wouldn't be testing what we were hoping to test with this bot.

In addition, ccache is enabled on this bot and should be roughly equivalent time wise to doing dirty builds, so it didn't feel like a bad thing to enable.

Hope that helps to explain the motivation behind this change.

**Comment by joker-eph** [comment]
> I was afraid that doing dirty builds may not get the CMake argument to stick so we wouldn't be testing what we were hoping to test with this bot.

So there is no evidence of anything wrong right now? It's just not clear why this bot in particular who be more sensitive to incremental build issue than any other?

> If you'd like to keep your personal email address private, you can use a noreply email address from GitHub as your commit email address. To use your noreply email address for commits you push from the command line, use that email address when you set your commit email address in Git. To use your noreply address for web-based Git operations, set your commit email address on GitHub and choose to Keep my email address private.

**Pull request merged**
