### PR TITLE
Add LIBC_INCLUDE_BENCHMARKS to fullbuild

### PR DESCRIPTION
**Pull request by gchatelet**
This is fixing the build bots now that https://reviews.llvm.org/D122481 has been submitted.

### CODE REVIEW

**Comment by sivachandra** [comment]
Can you please consider this approved and commit this directly? We use Phabricator for zorg also and reviews work exactly the same way if you want a review.

**Comment by sivachandra** [comment]
I have submitted this separately to get the bot to cycle green.

**Comment by gchatelet** [comment]
> Can you please consider this approved and commit this directly? We use Phabricator for zorg also and reviews work exactly the same way if you want a review.

Thx for submitting this while I was away.
I wasn't aware of the review process for zorg. Next time I'll submit this directly. Two more questions:
 - Is it sufficient to just push the commit to fix the issue (aka. are build bot fetching llvm-zorg at HEAD) or is there an additional process to make llvm-zorg available to build bots?
 - It seems that flags for llvm libc should be of the form `LLVM_LIBC_XXX`, do you want me to rename `LIBC_INCLUDE_BENCHMARKS` into `LLVM_LIBC_INCLUDE_BENCHMARKS` for consistency?

**Comment by sivachandra** [comment]
Yes, it is sufficient to push. The bots update the build scripts right at the beginning. For example, look at step 2 here: https://lab.llvm.org/buildbot/#/builders/163/builds/15168.

Normally, the `LLVM_` prefix is used for vars which represent something in the `llvm` directory or something `llvm-project` wide. For vars which affect something only in the `libc` directory, we should not have the `LLVM_` prefix. Take for example the vars in `clang` directory which affect only clang- they do not have a `LLVM_CLANG_` prefix.

**Pull request closed without merging**
