### PR TITLE
Update configuration for armv7l/aarch64 Win-to-Linux cross toolchain release builders.

### PR DESCRIPTION
**Pull request by vvereschaka**
Missed configuration for the workers hosting the release builders.

See #199 for details.

Related https://github.com/llvm/llvm-project/issues/94284

### CODE REVIEW

**Review by gkistanova — APPROVED** [review]
LGTM.

**Comment by vvereschaka** [comment]
Thank you @gkistanova , most likely I'll update these changes later. I found some problems with the compiler-rt builtin library tests and I'll need to do some changes accordingly later.
The PR is in Draft status now.

**Comment by gkistanova** [comment]
No worries. Please feel free to ping me whenever you are ready.

**Comment by vvereschaka** [comment]
@gkistanova would you take a look?

**Review by gkistanova — APPROVED** [review]
LGTM.

**Pull request merged**
